// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Ioj5jV-H-7vf1yseXegRvb11LbUAQs4',
    appId: '1:317390332047:web:59afb4ebf0f7b3e21810fa',
    messagingSenderId: '317390332047',
    projectId: 'field-flow-app-59e13',
    authDomain: 'field-flow-app-59e13.firebaseapp.com',
    storageBucket: 'field-flow-app-59e13.firebasestorage.app',
    measurementId: 'G-VDP2LHFEKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSB9yhGJwy1aggYzbPcHY7KpQK2Al9fA0',
    appId: '1:317390332047:android:e4fdbd4736b451eb1810fa',
    messagingSenderId: '317390332047',
    projectId: 'field-flow-app-59e13',
    storageBucket: 'field-flow-app-59e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9277Glasm3GC07aWRFIbXLTbsS4-YAkU',
    appId: '1:317390332047:ios:670c97f4cce1cf3d1810fa',
    messagingSenderId: '317390332047',
    projectId: 'field-flow-app-59e13',
    storageBucket: 'field-flow-app-59e13.firebasestorage.app',
    iosBundleId: 'com.example.fieldFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9277Glasm3GC07aWRFIbXLTbsS4-YAkU',
    appId: '1:317390332047:ios:670c97f4cce1cf3d1810fa',
    messagingSenderId: '317390332047',
    projectId: 'field-flow-app-59e13',
    storageBucket: 'field-flow-app-59e13.firebasestorage.app',
    iosBundleId: 'com.example.fieldFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Ioj5jV-H-7vf1yseXegRvb11LbUAQs4',
    appId: '1:317390332047:web:e782f86eaf0042751810fa',
    messagingSenderId: '317390332047',
    projectId: 'field-flow-app-59e13',
    authDomain: 'field-flow-app-59e13.firebaseapp.com',
    storageBucket: 'field-flow-app-59e13.firebasestorage.app',
    measurementId: 'G-WGNN8WPVDE',
  );
}
